version: '3'
services:
  apache:
    build: .docker/apache
    container_name: popp_apache
    restart: always
    ports:
    - 80:80
    volumes:
    - .docker/config/vhosts:/etc/apache2/sites-enabled
    - ./apps/popp:/home/www/popp
    depends_on:
    - php

  php:
    build: .docker/php
    container_name: popp_php
    restart: always
    volumes:
    - ./apps/popp/:/home/www/popp
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    depends_on:
    - postgres
        
  postgres:
    container_name: popp_postgres
    image: postgis/postgis:13-3.4
    restart: always
    ports:
    - "5432:5432"
    env_file:
      - ./apps/popp/.env # configure postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#    - 8080:8080

volumes:
  postgres-data: # named volumes can be managed easier using docker-compose
  

#  app:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#    depends_on:
#    - "db"
#    image: symfony
#    ports:
#    - 81:80
#    volumes:
#    - .:/app/
#    environment:
#      DATABASE_URL: "pgsql://postgres:uxK4(m8h@db:5432/popp"
#      APP_ENV: dev
#      APP_SECRET: "b9abc19ae10d53eb7cf5b5684ec6511f"
#      MAILER_URL: "null://localhost"
